# Generated by Django 4.1.7 on 2023-03-18 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugreport', '0002_contributor_project_contributors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('NONE', 'None'), ('READ', 'Read'), ('WRITE', 'Write')], default='NONE', max_length=5, validators=[django.core.validators.MaxLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50)]),
        ),
    ]
